/* ============================================================================
   AI Match — DATA FILE  (edit this file to manage the site)
   ----------------------------------------------------------------------------
   1) ADD A MODEL: copy a block in MODELS, paste, change fields. Order is free.
   2) AFFILIATE LINK: change a model's "link" — that's what its button opens.
   3) VERSIONS are separate entries (e.g. Claude Opus 4.8 vs Claude Sonnet 4.6).
   4) CONFIG (password, email, analytics, update date) is right below.

   cats vocab : chat writing coding images video music research design productivity
   strengths  : quality speed cost creative
   linkType   : "official" -> button "Open official site"
                "download" -> button "Download / run it"
   ========================================================================== */

window.CONFIG = {
  adminPassword: "change-this-password", // change before deploy (client-side gate, not real security)
  adminEmail: "onlyonecorpceo@gmail.com",
  ga4MeasurementId: "",                  // paste "G-XXXXXXX" to turn on real stats
  defaultLang: "en",
  lastUpdated: "2026-06-23"              // shown under the hero; bump it when you review models
};

window.MODELS = [
  /* ---- general chat / assistants ---- */
  {id:"gpt-5-5",name:"GPT-5.5",maker:"OpenAI",cats:["chat","writing","coding","research"],free:true,oss:false,strengths:["quality","creative"],weight:10,link:"https://chatgpt.com",linkType:"official",blurb:{en:"OpenAI's flagship — the most versatile all-rounder for writing, work, and everyday tasks.",ko:"OpenAI 플래그십 — 글쓰기·업무·일상까지 두루 강한 가장 다재다능한 올라운더."}},
  {id:"claude-opus-4-8",name:"Claude Opus 4.8",maker:"Anthropic",cats:["chat","coding","writing","research"],free:true,oss:false,strengths:["quality"],weight:10,link:"https://claude.ai",linkType:"official",blurb:{en:"Anthropic's top model — current leader for coding and long, careful reasoning.",ko:"Anthropic 최상위 모델 — 코딩과 길고 정교한 추론에서 현재 선두."}},
  {id:"claude-sonnet-4-6",name:"Claude Sonnet 4.6",maker:"Anthropic",cats:["chat","writing","coding"],free:true,oss:false,strengths:["creative","speed","cost"],weight:9,link:"https://claude.ai",linkType:"official",blurb:{en:"Near-Opus quality with the best writing style — faster and cheaper.",ko:"Opus에 가까운 품질에 최고의 문체, 더 빠르고 저렴합니다."}},
  {id:"gemini-3-1-pro",name:"Gemini 3.1 Pro",maker:"Google",cats:["chat","research","writing","images"],free:true,oss:false,strengths:["quality","cost"],weight:9,link:"https://gemini.google.com",linkType:"official",blurb:{en:"Leads reasoning benchmarks with a 1M-token context and native multimodal input.",ko:"100만 토큰 컨텍스트와 네이티브 멀티모달로 추론 벤치마크 선두."}},
  {id:"gemini-3-5-flash",name:"Gemini 3.5 Flash",maker:"Google",cats:["chat","writing"],free:true,oss:false,strengths:["speed","cost"],weight:8,link:"https://gemini.google.com",linkType:"official",blurb:{en:"The price-performance champion — fast, cheap, great for high volume.",ko:"가성비 챔피언 — 빠르고 저렴해 대량 작업에 좋습니다."}},
  {id:"grok-4-3",name:"Grok 4.3",maker:"xAI",cats:["chat","research","images"],free:true,oss:false,strengths:["cost","creative","speed"],weight:8,link:"https://grok.com",linkType:"official",blurb:{en:"Live X/web context with the fewest guardrails and aggressive pricing.",ko:"실시간 X·웹 반영, 가장 느슨한 제약과 공격적인 가격."}},
  {id:"deepseek-v4",name:"DeepSeek V4",maker:"DeepSeek",cats:["chat","coding","research"],free:true,oss:true,strengths:["cost"],weight:8,link:"https://huggingface.co/deepseek-ai",linkType:"download",blurb:{en:"Frontier-class results at a fraction of the cost; open weights you can self-host.",ko:"최상위급 성능을 매우 낮은 비용으로, 직접 호스팅 가능한 오픈 웨이트."}},
  {id:"qwen-3-7",name:"Qwen 3.7",maker:"Alibaba",cats:["chat","coding"],free:true,oss:true,strengths:["cost","quality"],weight:7,link:"https://huggingface.co/Qwen",linkType:"download",blurb:{en:"Strong multilingual open model, especially for coding and math.",ko:"다국어에 강한 오픈 모델, 특히 코딩·수학에 우수."}},
  {id:"glm-5",name:"GLM-5",maker:"Z.ai",cats:["chat","coding"],free:true,oss:true,strengths:["cost","quality"],weight:7,link:"https://huggingface.co/models?search=GLM",linkType:"download",blurb:{en:"Underrated open model with frontier-class coding, free to run.",ko:"저평가된 오픈 모델, 최상위급 코딩을 무료로 실행."}},
  {id:"llama",name:"Llama",maker:"Meta",cats:["chat","coding"],free:true,oss:true,strengths:["cost"],weight:7,link:"https://www.llama.com/llama-downloads/",linkType:"download",blurb:{en:"The most widely used open model family — run it privately on your own hardware.",ko:"가장 널리 쓰이는 오픈 모델 — 내 장비에서 프라이빗하게 실행."}},
  {id:"mistral",name:"Mistral / Le Chat",maker:"Mistral AI",cats:["chat","coding"],free:true,oss:true,strengths:["speed","cost"],weight:6,link:"https://huggingface.co/mistralai",linkType:"download",blurb:{en:"Fast, lean European open models with a free Le Chat web app.",ko:"빠르고 가벼운 유럽산 오픈 모델, 무료 Le Chat 웹앱 제공."}},
  {id:"copilot",name:"Microsoft Copilot",maker:"Microsoft",cats:["chat","writing","productivity"],free:true,oss:false,strengths:["speed"],weight:6,link:"https://copilot.microsoft.com",linkType:"official",blurb:{en:"AI baked into Windows and Office for everyday documents.",ko:"윈도우·오피스에 내장된 일상 문서용 AI."}},
  {id:"perplexity",name:"Perplexity",maker:"Perplexity",cats:["research","chat"],free:true,oss:false,strengths:["quality"],weight:8,link:"https://www.perplexity.ai",linkType:"official",blurb:{en:"Answers every question with cited sources — built for trustworthy research.",ko:"모든 답변에 출처를 달아주는, 신뢰할 수 있는 리서치 도구."}},

  /* ---- coding ---- */
  {id:"claude-code",name:"Claude Code (Opus 4.8)",maker:"Anthropic",cats:["coding"],free:false,oss:false,strengths:["quality"],weight:9,link:"https://www.anthropic.com/claude-code",linkType:"official",blurb:{en:"Agentic coding from your terminal — leads benchmarks on large projects.",ko:"터미널 기반 에이전트형 코딩 — 대형 프로젝트 벤치마크 선두."}},
  {id:"cursor",name:"Cursor",maker:"Anysphere",cats:["coding"],free:true,oss:false,strengths:["quality","speed"],weight:9,link:"https://cursor.com",linkType:"official",blurb:{en:"The most popular AI-native code editor for everyday development.",ko:"일상 개발에서 가장 인기 있는 AI 네이티브 코드 에디터."}},
  {id:"gh-copilot",name:"GitHub Copilot",maker:"GitHub",cats:["coding"],free:true,oss:false,strengths:["speed"],weight:8,link:"https://github.com/features/copilot",linkType:"official",blurb:{en:"The industry-standard pair programmer with the widest IDE support.",ko:"가장 폭넓은 IDE를 지원하는 업계 표준 페어 프로그래밍 도구."}},
  {id:"windsurf",name:"Windsurf",maker:"Windsurf",cats:["coding"],free:true,oss:false,strengths:["speed"],weight:6,link:"https://windsurf.com",linkType:"official",blurb:{en:"AI editor focused on smooth multi-file edits.",ko:"여러 파일을 매끄럽게 편집하는 데 집중한 AI 에디터."}},
  {id:"replit",name:"Replit Agent",maker:"Replit",cats:["coding"],free:true,oss:false,strengths:["speed"],weight:6,link:"https://replit.com",linkType:"official",blurb:{en:"Build and deploy small apps through conversation, in the browser.",ko:"대화만으로 작은 앱을 만들고 배포까지, 브라우저에서."}},

  /* ---- images ---- */
  {id:"gpt-image-2",name:"GPT Image 2",maker:"OpenAI",cats:["images"],free:true,oss:false,strengths:["quality"],weight:9,link:"https://chatgpt.com",linkType:"official",blurb:{en:"Best at prompt fidelity and rendering readable text inside images.",ko:"프롬프트 충실도와 이미지 내 또렷한 글자 표현에 최강."}},
  {id:"nano-banana-pro",name:"Nano Banana Pro",maker:"Google",cats:["images"],free:true,oss:false,strengths:["quality"],weight:8,link:"https://gemini.google.com",linkType:"official",blurb:{en:"4K photoreal images in seconds, with strong multilingual text.",ko:"수 초 만에 4K 사실적 이미지, 다국어 텍스트도 강함."}},
  {id:"midjourney-v7",name:"Midjourney v7",maker:"Midjourney",cats:["images"],free:false,oss:false,strengths:["creative","quality"],weight:9,link:"https://www.midjourney.com",linkType:"official",blurb:{en:"The king of artistic, cinematic image quality.",ko:"예술적·영화적 이미지 퀄리티의 제왕."}},
  {id:"firefly-4",name:"Adobe Firefly Image 4",maker:"Adobe",cats:["images","design"],free:true,oss:false,strengths:["quality"],weight:7,link:"https://www.adobe.com/products/firefly.html",linkType:"official",blurb:{en:"The safest for commercial work — licensed training data with IP indemnity.",ko:"라이선스 데이터+저작권 보호로 상업용에 가장 안전."}},
  {id:"ideogram-3",name:"Ideogram 3.0",maker:"Ideogram",cats:["images"],free:true,oss:false,strengths:["quality"],weight:7,link:"https://ideogram.ai",linkType:"official",blurb:{en:"The one tool that reliably renders legible text in images.",ko:"이미지 안 글자를 안정적으로 또렷하게 넣는 거의 유일한 도구."}},
  {id:"flux-2",name:"FLUX.2",maker:"Black Forest Labs",cats:["images"],free:true,oss:true,strengths:["quality","cost"],weight:8,link:"https://huggingface.co/black-forest-labs",linkType:"download",blurb:{en:"The leading open model for photorealistic images — self-host for free.",ko:"사실적 이미지에 강한 대표 오픈 모델 — 직접 호스팅하면 무료."}},
  {id:"sd-3-5",name:"Stable Diffusion 3.5",maker:"Stability AI",cats:["images"],free:true,oss:true,strengths:["cost","creative"],weight:7,link:"https://huggingface.co/stabilityai",linkType:"download",blurb:{en:"Maximum control and the biggest fine-tuning ecosystem, fully open.",ko:"최고의 제어력과 가장 큰 파인튜닝 생태계, 완전 오픈소스."}},
  {id:"leonardo",name:"Leonardo AI",maker:"Leonardo",cats:["images","design"],free:true,oss:false,strengths:["creative","cost"],weight:6,link:"https://leonardo.ai",linkType:"official",blurb:{en:"Generous free tier for game art, characters, and concepts.",ko:"게임 아트·캐릭터·콘셉트에 좋은 넉넉한 무료 플랜."}},
  {id:"recraft",name:"Recraft",maker:"Recraft",cats:["images","design"],free:true,oss:false,strengths:["quality"],weight:6,link:"https://www.recraft.ai",linkType:"official",blurb:{en:"Best for vectors and on-brand, repeatable design systems.",ko:"벡터와 브랜드 일관성 있는 디자인 시스템에 최적."}},

  /* ---- video ---- */
  {id:"veo-3-1",name:"Veo 3.1",maker:"Google DeepMind",cats:["video"],free:false,oss:false,strengths:["quality","creative"],weight:9,link:"https://labs.google/flow",linkType:"official",blurb:{en:"The leading text-to-video model, with native audio and cinematic quality.",ko:"오디오까지 생성하는 영화급 퀄리티의 대표 영상 모델."}},
  {id:"runway-gen4",name:"Runway Gen-4",maker:"Runway",cats:["video"],free:true,oss:false,strengths:["creative","quality"],weight:8,link:"https://runwayml.com",linkType:"official",blurb:{en:"The pro editor's choice with precise motion control.",ko:"정밀한 모션 제어로 전문 편집자가 선호하는 도구."}},
  {id:"kling",name:"Kling",maker:"Kuaishou",cats:["video"],free:true,oss:false,strengths:["quality","speed"],weight:7,link:"https://klingai.com",linkType:"official",blurb:{en:"Smooth, long clips that handle complex human motion well.",ko:"복잡한 인물 동작도 자연스러운 길고 매끄러운 영상."}},
  {id:"luma",name:"Luma Dream Machine",maker:"Luma AI",cats:["video"],free:true,oss:false,strengths:["speed"],weight:6,link:"https://lumalabs.ai/dream-machine",linkType:"official",blurb:{en:"Fast, accessible video generation that's easy to start with.",ko:"빠르고 접근성 좋아 시작하기 쉬운 영상 생성."}},
  {id:"pika",name:"Pika",maker:"Pika",cats:["video"],free:true,oss:false,strengths:["speed","creative"],weight:6,link:"https://pika.art",linkType:"official",blurb:{en:"Playful, quick short-form video with fun effects.",ko:"재미있는 효과의 빠른 숏폼 영상."}},

  /* ---- music & audio ---- */
  {id:"suno-v4-5",name:"Suno v4.5",maker:"Suno",cats:["music"],free:true,oss:false,strengths:["creative","quality"],weight:9,link:"https://suno.com",linkType:"official",blurb:{en:"Type a prompt, get a full studio-quality song with vocals.",ko:"프롬프트 한 줄로 보컬까지 갖춘 완성곡."}},
  {id:"udio",name:"Udio",maker:"Udio",cats:["music"],free:true,oss:false,strengths:["creative"],weight:7,link:"https://www.udio.com",linkType:"official",blurb:{en:"More granular control over stems and remixing.",ko:"스템 분리·리믹스 등 세밀한 제어."}},
  {id:"elevenlabs-v3",name:"ElevenLabs v3",maker:"ElevenLabs",cats:["music"],free:true,oss:false,strengths:["quality"],weight:8,link:"https://elevenlabs.io",linkType:"official",blurb:{en:"The most human-sounding AI voice and cloning, 70+ languages.",ko:"사람과 가장 흡사한 AI 음성·복제, 70개 이상 언어."}},

  /* ---- research & study ---- */
  {id:"notebooklm",name:"NotebookLM",maker:"Google",cats:["research","productivity"],free:true,oss:false,strengths:["quality"],weight:8,link:"https://notebooklm.google.com",linkType:"official",blurb:{en:"Upload your docs and get cited answers — even a podcast — from just them.",ko:"내 문서를 올리면 그 안에서만 출처 답변·팟캐스트 생성."}},
  {id:"consensus",name:"Consensus",maker:"Consensus",cats:["research"],free:true,oss:false,strengths:["quality"],weight:6,link:"https://consensus.app",linkType:"official",blurb:{en:"A search engine that answers from peer-reviewed papers.",ko:"동료 심사 논문에서 답을 찾아주는 검색 엔진."}},
  {id:"elicit",name:"Elicit",maker:"Elicit",cats:["research"],free:true,oss:false,strengths:["quality"],weight:6,link:"https://elicit.com",linkType:"official",blurb:{en:"Automates literature reviews — find, screen, extract.",ko:"논문 검색·선별·추출로 문헌 리뷰 자동화."}},

  /* ---- design & productivity ---- */
  {id:"figma",name:"Figma",maker:"Figma",cats:["design"],free:true,oss:false,strengths:["quality"],weight:8,link:"https://www.figma.com",linkType:"official",blurb:{en:"The dominant product-design tool, now with AI layout help.",ko:"AI 레이아웃 지원까지 더해진 대표 제품 디자인 도구."}},
  {id:"canva",name:"Canva",maker:"Canva",cats:["design","images","productivity"],free:true,oss:false,strengths:["speed","cost"],weight:8,link:"https://www.canva.com",linkType:"official",blurb:{en:"Magic Studio covers most non-designer needs in one place.",ko:"Magic Studio 하나로 비전문가 디자인 수요 대부분 해결."}},
  {id:"gamma",name:"Gamma",maker:"Gamma",cats:["design","productivity"],free:true,oss:false,strengths:["speed"],weight:7,link:"https://gamma.app",linkType:"official",blurb:{en:"Generate polished slide decks and docs from one prompt.",ko:"프롬프트 하나로 완성도 높은 슬라이드·문서 생성."}},
  {id:"framer",name:"Framer",maker:"Framer",cats:["design"],free:true,oss:false,strengths:["quality"],weight:6,link:"https://www.framer.com",linkType:"official",blurb:{en:"Design and publish a real website with AI, no code.",ko:"코드 없이 AI로 실제 웹사이트 디자인·게시."}},
  {id:"notion-ai",name:"Notion AI",maker:"Notion",cats:["productivity","writing"],free:false,oss:false,strengths:["speed"],weight:6,link:"https://www.notion.so/product/ai",linkType:"official",blurb:{en:"Writing and Q&A built into your notes and workspace.",ko:"메모·워크스페이스에 내장된 글쓰기·질의응답."}},
  /* ---- broader catalog: affiliate/referral-friendly tools ---- */
  {id:"jasper",name:"Jasper",maker:"Jasper",cats:["writing","productivity"],free:false,oss:false,strengths:["quality"],weight:6,link:"https://www.jasper.ai",linkType:"official",blurb:{en:"Marketing-focused writing platform with brand voice and templates.",ko:"브랜드 보이스·템플릿을 갖춘 마케팅 특화 글쓰기 플랫폼."}},
  {id:"copy-ai",name:"Copy.ai",maker:"Copy.ai",cats:["writing"],free:true,oss:false,strengths:["speed"],weight:5,link:"https://www.copy.ai",linkType:"official",blurb:{en:"Fast marketing copy and go-to-market workflows.",ko:"마케팅 카피와 GTM 워크플로를 빠르게 생성."}},
  {id:"writesonic",name:"Writesonic",maker:"Writesonic",cats:["writing"],free:true,oss:false,strengths:["speed"],weight:5,link:"https://writesonic.com",linkType:"official",blurb:{en:"SEO-friendly articles and ad copy at speed.",ko:"SEO 친화적인 글과 광고 카피를 빠르게."}},
  {id:"quillbot",name:"QuillBot",maker:"QuillBot",cats:["writing"],free:true,oss:false,strengths:["speed"],weight:5,link:"https://quillbot.com",linkType:"official",blurb:{en:"Paraphrasing, summarizing, and grammar polish.",ko:"패러프레이징·요약·문법 다듬기에 특화."}},
  {id:"grammarly",name:"Grammarly",maker:"Grammarly",cats:["writing"],free:true,oss:false,strengths:["quality"],weight:6,link:"https://www.grammarly.com",linkType:"official",blurb:{en:"The standard for grammar, clarity, and tone fixes as you type.",ko:"입력하는 동안 문법·명료성·어조를 바로잡아 주는 표준 도구."}},
  {id:"sudowrite",name:"Sudowrite",maker:"Sudowrite",cats:["writing"],free:false,oss:false,strengths:["creative"],weight:5,link:"https://www.sudowrite.com",linkType:"official",blurb:{en:"Built for fiction — brainstorm, expand, and rewrite story prose.",ko:"소설 집필 특화 — 아이디어·확장·문장 리라이팅."}},
  {id:"surfer-seo",name:"Surfer SEO",maker:"Surfer",cats:["writing","productivity"],free:false,oss:false,strengths:["quality"],weight:5,link:"https://surferseo.com",linkType:"official",blurb:{en:"Optimize articles to rank, with data-driven content briefs.",ko:"데이터 기반 콘텐츠 가이드로 검색 상위 노출을 위한 글 최적화."}},
  {id:"synthesia",name:"Synthesia",maker:"Synthesia",cats:["video"],free:false,oss:false,strengths:["quality"],weight:7,link:"https://www.synthesia.io",linkType:"official",blurb:{en:"Turn scripts into studio videos with realistic AI avatars, 140+ languages.",ko:"대본을 사실적인 AI 아바타 영상으로, 140개 이상 언어 지원."}},
  {id:"heygen",name:"HeyGen",maker:"HeyGen",cats:["video"],free:true,oss:false,strengths:["quality"],weight:7,link:"https://www.heygen.com",linkType:"official",blurb:{en:"AI avatars and instant video translation with lip-sync.",ko:"AI 아바타와 입모양까지 맞추는 즉석 영상 번역."}},
  {id:"descript",name:"Descript",maker:"Descript",cats:["video","music"],free:true,oss:false,strengths:["quality"],weight:7,link:"https://www.descript.com",linkType:"official",blurb:{en:"Edit video and podcasts by editing the transcript — like a doc.",ko:"자막을 문서처럼 편집해 영상·팟캐스트를 손쉽게 편집."}},
  {id:"opus-clip",name:"Opus Clip",maker:"Opus",cats:["video"],free:true,oss:false,strengths:["speed"],weight:6,link:"https://www.opus.pro",linkType:"official",blurb:{en:"Turns long videos into viral short clips automatically.",ko:"긴 영상을 자동으로 바이럴 숏클립으로 변환."}},
  {id:"invideo",name:"InVideo AI",maker:"InVideo",cats:["video"],free:true,oss:false,strengths:["speed"],weight:5,link:"https://invideo.io",linkType:"official",blurb:{en:"Make full videos from a text prompt, with voiceover and edits.",ko:"텍스트 프롬프트로 보이스오버·편집까지 갖춘 영상 제작."}},
  {id:"pictory",name:"Pictory",maker:"Pictory",cats:["video"],free:false,oss:false,strengths:["speed"],weight:5,link:"https://pictory.ai",linkType:"official",blurb:{en:"Repurpose blogs and scripts into short videos fast.",ko:"블로그·대본을 빠르게 숏폼 영상으로 재가공."}},
  {id:"krea",name:"Krea",maker:"Krea",cats:["images"],free:true,oss:false,strengths:["creative"],weight:6,link:"https://www.krea.ai",linkType:"official",blurb:{en:"Real-time, controllable image and video generation for creatives.",ko:"실시간·정교한 제어가 가능한 크리에이터용 이미지·영상 생성."}},
  {id:"photoroom",name:"Photoroom",maker:"Photoroom",cats:["images","design"],free:true,oss:false,strengths:["speed"],weight:6,link:"https://www.photoroom.com",linkType:"official",blurb:{en:"Instant background removal and product photos for shops.",ko:"배경 제거와 상품 사진을 즉석에서 — 쇼핑몰에 최적."}},
  {id:"playground",name:"Playground",maker:"Playground",cats:["images"],free:true,oss:false,strengths:["cost"],weight:5,link:"https://playground.com",linkType:"official",blurb:{en:"Free-friendly image generation and editing for social graphics.",ko:"소셜 그래픽용 이미지 생성·편집, 무료 활용도 좋음."}},
  {id:"clipdrop",name:"Clipdrop",maker:"Clipdrop",cats:["images"],free:true,oss:false,strengths:["speed"],weight:5,link:"https://clipdrop.co",linkType:"official",blurb:{en:"A toolbox of one-tap image edits: cleanup, upscale, relight.",ko:"정리·업스케일·조명 보정 등 한 번에 처리하는 이미지 도구함."}},
  {id:"looka",name:"Looka",maker:"Looka",cats:["design"],free:false,oss:false,strengths:["speed"],weight:5,link:"https://looka.com",linkType:"official",blurb:{en:"Generate a logo and full brand kit in minutes.",ko:"몇 분 만에 로고와 브랜드 키트를 생성."}},
  {id:"murf",name:"Murf",maker:"Murf",cats:["music"],free:true,oss:false,strengths:["quality"],weight:6,link:"https://murf.ai",linkType:"official",blurb:{en:"Studio-grade AI voiceovers for videos and presentations.",ko:"영상·프레젠테이션용 스튜디오급 AI 보이스오버."}},
  {id:"speechify",name:"Speechify",maker:"Speechify",cats:["music"],free:true,oss:false,strengths:["speed"],weight:5,link:"https://speechify.com",linkType:"official",blurb:{en:"Turns any text or document into natural speech to listen on the go.",ko:"어떤 글·문서든 자연스러운 음성으로 바꿔 들려줌."}},
  {id:"play-ht",name:"Play.ht",maker:"PlayHT",cats:["music"],free:true,oss:false,strengths:["quality"],weight:5,link:"https://play.ht",linkType:"official",blurb:{en:"Realistic text-to-speech and voice cloning for creators.",ko:"사실적인 음성 합성과 음성 복제를 제공."}},
  {id:"landr",name:"LANDR",maker:"LANDR",cats:["music"],free:true,oss:false,strengths:["quality"],weight:4,link:"https://www.landr.com",linkType:"official",blurb:{en:"Instant AI mastering and tools for musicians.",ko:"즉석 AI 마스터링과 뮤지션용 도구."}},
  {id:"otter",name:"Otter.ai",maker:"Otter.ai",cats:["research","productivity"],free:true,oss:false,strengths:["quality"],weight:6,link:"https://otter.ai",linkType:"official",blurb:{en:"Live meeting transcription with summaries and action items.",ko:"회의를 실시간 받아쓰고 요약·할 일까지 정리."}},
  {id:"fireflies",name:"Fireflies.ai",maker:"Fireflies",cats:["research","productivity"],free:true,oss:false,strengths:["quality"],weight:5,link:"https://fireflies.ai",linkType:"official",blurb:{en:"Records, transcribes, and searches your meetings across apps.",ko:"회의를 녹음·받아쓰고 앱 전반에서 검색 가능."}},
  {id:"scispace",name:"SciSpace",maker:"SciSpace",cats:["research"],free:true,oss:false,strengths:["quality"],weight:5,link:"https://scispace.com",linkType:"official",blurb:{en:"Read and understand research papers with an AI copilot.",ko:"AI 코파일럿으로 논문을 읽고 이해하도록 도와줌."}},
  {id:"lovable",name:"Lovable",maker:"Lovable",cats:["coding"],free:true,oss:false,strengths:["speed"],weight:6,link:"https://lovable.dev",linkType:"official",blurb:{en:"Describe an app and get a working full-stack web app.",ko:"앱을 설명하면 동작하는 풀스택 웹앱을 만들어 줌."}},
  {id:"bolt",name:"Bolt",maker:"StackBlitz",cats:["coding"],free:true,oss:false,strengths:["speed"],weight:6,link:"https://bolt.new",linkType:"official",blurb:{en:"Prompt-to-app in the browser, with instant deploy.",ko:"브라우저에서 프롬프트로 앱을 만들고 즉시 배포."}},
  {id:"v0",name:"v0",maker:"Vercel",cats:["coding","design"],free:true,oss:false,strengths:["speed"],weight:6,link:"https://v0.app",linkType:"official",blurb:{en:"Generate polished UI and React components from a prompt.",ko:"프롬프트로 깔끔한 UI·React 컴포넌트를 생성."}},
  {id:"beautiful-ai",name:"Beautiful.ai",maker:"Beautiful.ai",cats:["design","productivity"],free:false,oss:false,strengths:["quality"],weight:5,link:"https://www.beautiful.ai",linkType:"official",blurb:{en:"Presentations that design themselves as you add content.",ko:"내용을 넣으면 알아서 디자인되는 프레젠테이션."}},
  {id:"motion",name:"Motion",maker:"Motion",cats:["productivity"],free:false,oss:false,strengths:["speed"],weight:5,link:"https://www.usemotion.com",linkType:"official",blurb:{en:"AI that auto-plans your calendar and tasks each day.",ko:"매일 일정과 할 일을 자동으로 계획해 주는 AI."}},
  {id:"taskade",name:"Taskade",maker:"Taskade",cats:["productivity"],free:true,oss:false,strengths:["speed"],weight:5,link:"https://www.taskade.com",linkType:"official",blurb:{en:"AI workspace for notes, tasks, and team agents.",ko:"메모·할 일·팀 에이전트를 위한 AI 워크스페이스."}},
  {id:"zapier",name:"Zapier",maker:"Zapier",cats:["productivity"],free:true,oss:false,strengths:["speed"],weight:6,link:"https://zapier.com",linkType:"official",blurb:{en:"Connect 7,000+ apps and automate workflows, now with AI agents.",ko:"7,000개 이상 앱을 연결해 워크플로 자동화, AI 에이전트 지원."}},
  {id:"make",name:"Make",maker:"Make",cats:["productivity"],free:true,oss:false,strengths:["cost"],weight:5,link:"https://www.make.com",linkType:"official",blurb:{en:"Visual, low-cost automation for complex multi-step workflows.",ko:"복잡한 다단계 워크플로를 시각적으로·저렴하게 자동화."}},
];
